//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace linq2dbTest02
{
	/// <summary>
	/// Database       : TestBase
	/// Data Source    : .
	/// Server Version : 15.00.2000
	/// </summary>
	public partial class TestBaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<User>     Users     { get { return this.GetTable<User>(); } }
		public ITable<UserInfo> UserInfos { get { return this.GetTable<UserInfo>(); } }

		public TestBaseDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestBaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestBaseDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestBaseDB(LinqToDBConnectionOptions<TestBaseDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity] public int    UserId   { get; set; } // int
		[Column,     Nullable] public string UserName { get; set; } // nchar(10)
		[Column,     Nullable] public int?   UserPwd  { get; set; } // int
		[Column,     Nullable] public int?   Age      { get; set; } // int
		[Column,     Nullable] public int?   DeptId   { get; set; } // int
	}

	[Table(Schema="dbo", Name="UserInfos")]
	public partial class UserInfo
	{
		[PrimaryKey, Identity] public int    UserId   { get; set; } // int
		[Column,     Nullable] public string UserName { get; set; } // nchar(10)
		[Column,     Nullable] public int?   Age      { get; set; } // int
		[Column,     Nullable] public int?   DeptId   { get; set; } // int
		[Column,     Nullable] public int?   UserPwd  { get; set; } // int
	}

	public static partial class TableExtensions
	{
		public static User Find(this ITable<User> table, int UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}

		public static UserInfo Find(this ITable<UserInfo> table, int UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}
